dh_matrix:
  - [0.0, 90.0, 0.089159, 0.0]
  - [-0.425, 0.0, 0.0, 0.0]
  - [-0.39225, 0.0, 0.0, 0.0]
  - [0.0, 90.0, 0.10915, 0.0]
  - [0.0, -90.0, 0.09465, 0.0]
  - [0.0, 0.0, 0.3008, 0.0]

joint_limits:
  - [-180.0, 180.0]  # Shoulder joint
  - [-90.0, 90.0]    # Upper arm joint
  - [-90.0, 90.0]    # Forearm joint
  - [-180.0, 180.0]  # Wrist 1
  - [-180.0, 180.0]  # Wrist 2
  - [-180.0, 180.0]  # Wrist 3

xml_file:
  "universal_robots_ur5e/scene.xml"

robot_name:
  "ur5e_manipulator_arm"